import java.util.HashMap;

public class Item {
    
	public enum ItemList {
		Wood,
		Stone,
		IronOre,
		GoldOre,
		Coal,
		CoalAlt,
		Flower,
		Fiber,
		Poop,
		Bone,
		Jelly,
		BottledTorchbug,
		BottledBeetle,
		NightShade,
		BottledButterfly,
		Lavender,
		Crystal,
		BottledDeathMoth,
		Cinderbloom,
		DemonHorn,
		Thread,
		Hide,
		Sand,
		Brick,
		IronIngot,
		GoldIngot,
		Paper,
		Leather,
		Steel,
		SteelAlt,
		Glass,
		Ruby,
		Emerald,
		Topaz,
		Amethyst,
		BottledOil,
		Wheat,
		Flour,
		Plastic,
		RoyalSteel,
		RoyalClothing,
		FiberGlass,
		Electronics,
		Transmutation,
		GreenPigment,
		PurplePigment,
		Fossil,
		Sphynx,
		Kapala,
		FrozenRelic,
		Anchor,
		SunkenAnkh,
		GoldenEgg,
		BottledWater,
		Berry,
		Citrus,
		Beet,
		Sugar,
		Cheese,
		Mayo,
		Egg,
		BottledMilk,
		Meat,
		BottledFairy,
		CactusFruit,
		HotPepper,
		Pumpkin,
		Fish,
		Seaweed,
		Bread,
		Pizza,
		Cookies,
		Sushi,
		Soup,
		Sandwich,
		FruitSalad,
		IceCream,
		MeatSkewer,
		DinoEgg,
		SkeletonFish,
		FrozenSquid,
		LavaEel,
		CookedFish,
		CookedMeat,
		Arrow,
		Bomb,
		EMPGrenade,
		AnimalFeed,
		HealingPotion,
		Thunderbolt,
		AnasDelight,
		LiquidLuck,
		DraughtOfWisdom,
		Mandragora,
		BloodFuryCocktail,
		DragonPhiltre,
		GreedyMixture,
		SageScroll,
		BuilderScroll,
		DruidScroll,
		WizardScroll,
		MinerScroll,
		DemonScroll,
		SeedTree,
		SeedCotton,
		SeedBeet,
		SeedWheat,
		SeedHotPepper,
		SeedPumpkin,
		BottledRainbow,
		Key,
		Coin,
		Bottle,
		Droid,
		BasicPickaxe,
		SlimePickaxe,
		GoldenPickaxe,
		SkullPickaxe,
		CrystalPickaxe,
		DemonPickaxe,
		BasicShovel,
		SlimeSword,
		GoldenSword,
		SkullSword,
		CrystalSword,
		DemonSword,
		SlimeBow,
		GoldenBow,
		SkullBow,
		CrystalBow,
		SlimeAmulet,
		GoldenAmulet,
		SkullAmulet,
		CrystalAmulet,
		DemonAmulet,
		SlimeBoots,
		GoldenBoots,
		SkullBoots,
		CrystalBoots,
		SlimeGloves,
		GoldenGloves,
		SkullGloves,
		CrystalGloves,
		MoldyBook,
		SlimyTome,
		Necronomicon,
		GlacialScriptures,
		HellfireGlyphs,
		BasicBackpack,
		SmallBackpack,
		MediumBackpack,
		BigBackpack,
		HugeBackpack,
		TycoonBackpack,
		BasicWallet,
		SlimeWallet,
		GoldenWallet,
		SkullWallet,
		CrystalWallet,
		DemonWallet,
		SealOne,
		SealTwo,
		SealThree,
		SealFour,
		SealFive,
		SealSix,
		SealSeven,
		SealEight,
		SealNine,
		Glasses,
		TopHat,
		PinkBow,
		Lantern,
		SkeletonKey,
		SkeletonMask,
		FairyAura,
		Quiver,
		VampireWings,
		Shield,
		MagicScepter,
		Halo,
		ThunderRod,
		IceRod,
		FireRod,
		StaminaVessel,
		Heart,
		Landfill,
		WaterShovel,
		NomadShovel,
		RoyalShovel,
		RoboticShovel,
		GreatSkull,
		SpiritOrb,
		NecroRod,
		Obliterator,
		MeteorRod,
		StormRod,
		BlizzardRod,
		DeathRod,
		Fence,
		Gate,
		Bed,
		Torch,
		Bench,
		Throne,
		FairyStatue,
		BeetStatue,
		DisplayCase,
		FlowerPot,
		Road,
		Obsidian,
		StarFragment,
		VoidStone,
		LegendaryGem,
		VoidSteel,
		CosmicSteel,
		VoidRose,
		KrakenEye,
		AnimalLure,
		VoidPortal,
		BlueDye,
		TealDye,
		LimeDye,
		GreenDye,
		YellowDye,
		OrangeDye,
		RedDye,
		PinkDye,
		PurpleDye,
		GrayDye,
		BlackDye,
		DyeRemover,
		RepairKit,
		SeedBerry,
		SpikeTrap,
		Railroad,
		Locomotive,
		SigilSlime,
		SigilSkull,
		SigilFlame,
		SigilBeet,
		SigilStar,
		SigilDestroyer,
		TrainingDummy,
		Signpost,
		StarScroll,
		StoneFloor,
		StoneGate,
		StoneWall,
		IronFloor,
		IronGate,
		IronWall,
		SlimeFloor,
		SlimeGate,
		SlimeWall,
		BrickFloor,
		BrickGate,
		BrickWall,
		GlassFloor,
		GlassGate,
		GlassWall,
		SteelFloor,
		SteelGate,
		SteelWall,
		RoyalFloor,
		RoyalGate,
		RoyalWall,
		PlasticFloor,
		PlasticGate,
		PlasticWall,
		ElectronicFloor,
		ElectronicGate,
		ElectronicWall,
		VoidFloor,
		VoidGate,
		VoidWall,
		CosmicFloor,
		CosmicGate,
		CosmicWall,
		Hammer,
		FishingRod,
		VoidPickaxe,
		CosmicPickaxe,
		VoidSword,
		CosmicSword,
		DemonBow,
		VoidBow,
		CosmicBow,
		VoidWallet,
		CosmicWallet,
		DemonGloves,
		VoidGloves,
		CosmicGloves,
		DemonBoots,
		VoidBoots,
		CosmicBoots,
		VoidGuide,
		MagnumOpus,
		VoidAmulet,
		CosmicAmulet,
		FishNet,
		MerchantMedallion,
		LunarMedallion,
		NuclearPickaxe,
		NuclearSword,
		NuclearBow,
		NuclearWallet,
		NuclearGloves,
		NuclearBoots,
		NuclearCodex,
		NuclearAmulet,
		Uranium,
		ToxicSludge,
		OnyxRelic,
		NuclearFuelCell,
		NuclearMachinery,
		AtomicBomb,
		SigilToxic,
		SeedFlower
	}
	
	public int index = 0;
	public String name = "";
	public String description = "";
	//public Sprite = 
	public String type = "undefined";
	public String subType = "undefined";
	public double value = 0;
	public int healing = 0;
	public int energy = 0;
	
	
	public HashMap<String, Integer> bluePrint = new HashMap<String, Integer>();
	public String onUse = "undefined";
	public double craftingTime = 0;
	public boolean unlocked = true;
	public int damage = 0;
	public String structure = "undefined";
	public String tilemap = "undefined";
	public int onDestroySound = 0;

    Item(int index, String name, String description, String type, String subType, double value, int healing, int energy, HashMap bluePrint, String onUse, double craftingTime, boolean unlocked, int damage, String structure, String tilemap, int onDestroySound) {
        
    	this.index = index;
    	this.name = name;
    	this.description = description;
    	this.type = type;
    	this.subType = subType;
    	this.value = value;
    	this.healing = healing;
    	this.energy = energy;
    	this.bluePrint = bluePrint;
    	this.onUse = onUse;
    	this.craftingTime = craftingTime;
    	this.unlocked = unlocked;
    	this.damage = damage;
    	this.structure = structure;
    	this.tilemap = tilemap;
    	this.onDestroySound = onDestroySound;

    }
    
}
